/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    AIDetectionVerifier: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isAIGenerated",
              type: "bool",
            },
          ],
          name: "ContentVerified",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_contentHash",
              type: "bytes32",
            },
          ],
          name: "getVerificationResult",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "verifications",
          outputs: [
            {
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "isAIGenerated",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_contentHash",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "_isAIGenerated",
              type: "bool",
            },
          ],
          name: "verifyContent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
